//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycles.ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class D010MCSEntities : DbContext
    {
        public D010MCSEntities()
            : base("name=D010MCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tmake> tmakes { get; set; }
        public virtual DbSet<tmodel> tmodels { get; set; }
        public virtual DbSet<tservice> tservices { get; set; }
        public virtual DbSet<tstyle> tstyles { get; set; }
        public virtual DbSet<tyear> tyears { get; set; }
    }
}
