//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycles.ef
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class tservice
	{
		public tservice()
		{
			crt_dt = DateTime.Now;
		}
		[Display(Name = "Service ID")]
		public int srvc_id { get; set; }

		[Display(Name = "Service")]
		public string srvc_na { get; set; }

		[DataType(DataType.DateTime)]
		[Display(Name = "Date Created")]
		public System.DateTime crt_dt { get; set; }
	}
}
